// Global Style Css
import './globals.css'
// Google Fonts
import { Poppins } from 'next/font/google';


// Google Fonts
const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '500', '700', '900'] });

// Meta Tags
export const metadata = {
  title: 'Login_Webullish',
  description: 'Generated by Webulish',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {children}
      </body>
    </html>
  )
}
