// Global Style Css
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
// Google Fonts
import { Poppins } from "next/font/google";
// Toastify
import ToastifyContainerLayout from "./components/toastify/ToastifyContainer";
// Theme
import ProviderTheme from "./providers";
// Google Fonts
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "700", "900"],
});
// Meta Tags
export const metadata = {
  title: "Login_Webullish",
  description: "Generated by Webulish",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <ToastifyContainerLayout />
        {children}
      </body>
    </html>
  );
}
