'use client';
// Global Style Css
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { useState, useEffect } from "react";
// Toastify
import { ToastContainer } from "react-toastify";
// Google Fonts
import { Poppins } from "next/font/google";
// Google Fonts
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "700", "900"],
});
// Meta Tags
export const metadata = {
  title: "Login_Webullish",
  description: "Generated by Webulish",
};

export default function RootLayout({ children }) {
  const [isLoading, setIsLoading] = useState(false);

  // Avoid hydration error
  useEffect(() => {
    setIsLoading(true);
  }, [])
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {isLoading && <ToastContainer limit={1} position="bottom-center" autoClose={1000} />}
        {children}
      </body>
    </html>
  );
}
